const API = "http://127.0.0.1:8000";
const token = localStorage.getItem("orator_token");
const user = JSON.parse(localStorage.getItem("orator_user") || "null");
const $ = (selector) => document.querySelector(selector);
if (!token || !user) window.location.replace("index.html");
const authHeaders = () => ({ "Content-Type": "application/json", Authorization: `Bearer ${token}` });
async function api(path, options = {}) { const response = await fetch(`${API}${path}`, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || "Something went wrong."); return data; }
const roleCopy = (role) => ({ Learner: "Shape your voice through deliberate practice.", Coach: "Guide learners toward their clearest thinking.", Educator: "Create space for thoughtful, confident speakers.", Admin: "Oversee the people and practice within your platform." }[role] || "Your practice space is ready.");
const names = { clarity: "Clarity", confidence: "Confidence", argumentation: "Argumentation", rebuttal: "Rebuttal", delivery: "Delivery" };
function renderProfile(profile) { $("#profileSummary").hidden = false; $("#profileName").textContent = profile.name; $("#profileExperience").textContent = profile.experience; $("#profileGoals").textContent = profile.goals; $("#profileTopics").textContent = profile.preferred_topics.join(", "); $("#focusTitle").textContent = "Your practice is taking shape."; $("#focusBody").textContent = "Your speaker profile is ready. Return any time to refine the direction of your work."; $("#focusAction").innerHTML = "Refine profile <span>→</span>"; ["name", "experience", "goals"].forEach((key) => $("#profileForm").elements[key].value = profile[key]); $("#profileForm").elements.topics.value = profile.preferred_topics.join(", "); $("#profileForm").elements.domains.value = (profile.presentation_domains || []).join(", "); $("#profileForm").elements.coaching_preference.value = profile.coaching_preference || "Self-guided"; }
async function loadProfile() { try { renderProfile(await api("/profile", { headers: authHeaders() })); } catch (error) { if (!error.message.includes("Profile not found")) console.warn(error); } }
function renderSkills(skills) { $("#skillsList").innerHTML = Object.entries(names).map(([key, label]) => `<div class="skill-row"><label for="skill-${key}">${label}</label><input id="skill-${key}" data-skill="${key}" type="range" min="0" max="100" value="${skills[key]}"><output>${skills[key]}</output></div>`).join(""); document.querySelectorAll("[data-skill]").forEach((input) => input.addEventListener("input", () => input.nextElementSibling.value = input.value)); }
async function loadSkills() { renderSkills(await api("/skills", { headers: authHeaders() })); }
function renderGoals(goals) { const container = $("#goalsList"); container.classList.toggle("empty-state", goals.length === 0); container.innerHTML = goals.length ? goals.map((goal) => `<label class="feed-item"><span><input class="goal-check" data-goal="${goal.id}" type="checkbox" ${goal.completed ? "checked" : ""}> <strong>${goal.title}</strong>${goal.target_date ? `<span>Target: ${goal.target_date}</span>` : ""}</span><span>${goal.completed ? "Done" : "In progress"}</span></label>`).join("") : "No goals yet — add the first one."; document.querySelectorAll("[data-goal]").forEach((input) => input.addEventListener("change", async () => { await api(`/learning-goals/${input.dataset.goal}`, { method: "PATCH", headers: authHeaders(), body: JSON.stringify({ completed: input.checked }) }); loadGoals(); })); }
async function loadGoals() { renderGoals(await api("/learning-goals", { headers: authHeaders() })); }
function renderHistory(items, kind) { const container = $(kind === "debate" ? "#debatesList" : "#presentationsList"); container.classList.toggle("empty-state", items.length === 0); container.innerHTML = items.length ? items.slice(0, 5).map((item) => `<div class="feed-item"><span><strong>${kind === "debate" ? item.topic : item.title}</strong><span>${kind === "debate" ? item.position : item.domain} · ${new Date(item.created_at + "Z").toLocaleDateString()}</span></span><span class="score-pill">${item.score == null ? "Logged" : `${item.score}/100`}</span></div>`).join("") : (kind === "debate" ? "Your completed debates will appear here." : "Your presentations will appear here."); }
async function loadHistory() { const [debates, presentations] = await Promise.all([api("/debates", { headers: authHeaders() }), api("/presentations", { headers: authHeaders() })]); renderHistory(debates, "debate"); renderHistory(presentations, "presentation"); }
function renderManagement(overview) { $("#managementCard").hidden = false; $("#managementLink").hidden = false; $("#roleCounts").innerHTML = Object.entries(overview.counts).map(([role, count]) => `<div class="role-count"><strong>${count}</strong><span>${role}${count === 1 ? "" : "s"} registered</span></div>`).join(""); $("#managementUsers").innerHTML = overview.users.length ? overview.users.map((account) => `<div class="managed-user"><strong>${account.name}</strong><span>${account.role} · ${account.email}</span></div>`).join("") : "<span class=\"muted\">No lower-level accounts have registered yet.</span>"; }
async function loadManagement() { if (["Admin", "Educator", "Coach"].includes(user.role)) renderManagement(await api("/management/overview", { headers: authHeaders() })); }
async function initialise() { $("#emailText").textContent = user.email; $("#roleLabel").textContent = `${user.role.toUpperCase()} SPACE`; $("#roleCard").textContent = user.role; $("#roleDescription").textContent = roleCopy(user.role); try { if (user.role === "Learner") $("#welcomeTitle").textContent = (await api("/learner/dashboard", { headers: authHeaders() })).message; else if (["Coach", "Educator"].includes(user.role)) $("#welcomeTitle").textContent = (await api("/guidance/learners", { headers: authHeaders() })).message; else $("#welcomeTitle").textContent = "Platform overview."; await Promise.all([loadProfile(), loadSkills(), loadGoals(), loadHistory(), loadManagement()]); } catch (error) { $("#accessMessage").textContent = error.message; if (error.message.includes("access token")) { localStorage.clear(); window.location.replace("index.html"); } } }
const openProfile = () => $("#profileDialog").showModal();
$("#editProfileBtn").addEventListener("click", openProfile); $("#focusAction").addEventListener("click", openProfile); $(".close-button").addEventListener("click", () => $("#profileDialog").close());
$("#profileForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const split = (name) => form.get(name).split(",").map((item) => item.trim()).filter(Boolean); const payload = { name: form.get("name"), experience: form.get("experience"), goals: form.get("goals"), preferred_topics: split("topics"), presentation_domains: split("domains"), coaching_preference: form.get("coaching_preference") }; try { renderProfile(await api("/profile", { method: "PUT", headers: authHeaders(), body: JSON.stringify(payload) })); $("#profileMessage").textContent = "Saved."; setTimeout(() => $("#profileDialog").close(), 450); } catch (error) { $("#profileMessage").textContent = error.message; } });
$("#saveSkillsBtn").addEventListener("click", async () => { const payload = Object.fromEntries(Object.keys(names).map((key) => [key, Number($(`#skill-${key}`).value)])); await api("/skills", { method: "PUT", headers: authHeaders(), body: JSON.stringify(payload) }); $("#saveSkillsBtn").textContent = "Saved"; setTimeout(() => $("#saveSkillsBtn").textContent = "Save scores", 1000); });
$("#goalForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await api("/learning-goals", { method: "POST", headers: authHeaders(), body: JSON.stringify(Object.fromEntries(form)) }); event.currentTarget.reset(); loadGoals(); });
$("#debateForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); form.score = form.score ? Number(form.score) : null; await api("/debates", { method: "POST", headers: authHeaders(), body: JSON.stringify(form) }); event.currentTarget.reset(); loadHistory(); });
$("#presentationForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget)); form.score = form.score ? Number(form.score) : null; await api("/presentations", { method: "POST", headers: authHeaders(), body: JSON.stringify(form) }); event.currentTarget.reset(); loadHistory(); });
$("#signOutBtn").addEventListener("click", () => { localStorage.removeItem("orator_token"); localStorage.removeItem("orator_user"); window.location.href = "index.html"; });
initialise();
