import { useEffect, useState } from "react";
import api from "../services/api";
import {
  History as HistoryIcon,
  MessageSquare,
  FileText,
  ChevronDown,
  ChevronUp,
  Sun,
  Moon,
} from "lucide-react";
import { useTheme } from "../hooks/useTheme";

export default function History() {
  const [history, setHistory] = useState<any[]>([]);
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const { theme, toggleTheme } = useTheme();
  const dark = theme === "dark";

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const res = await api.get("/history");
      setHistory(res.data);
    } catch (err) {
      console.error(err);
    }
  };

  const toggleItem = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <div
      className={`min-h-screen transition-colors duration-300 ${
        dark
          ? "bg-[#020817] text-white"
          : "bg-slate-50 text-slate-900"
      }`}
    >
      {/* Header */}
      <header
        className={`border-b backdrop-blur-xl ${
          dark
            ? "border-slate-800/80 bg-[#020817]/90"
            : "border-slate-200 bg-white/90"
        }`}
      >
        <div className="max-w-7xl mx-auto px-6 lg:px-10 py-5">
          <div className="flex items-center justify-between gap-4">

            <div>
              <h1
                className={`text-2xl font-semibold tracking-wide ${
                  dark ? "text-white" : "text-slate-900"
                }`}
              >
                ORATIO AI
              </h1>

              <p className="text-xs text-slate-500 mt-1 tracking-[0.2em] uppercase">
                Communication Intelligence
              </p>
            </div>

            <div className="flex items-center gap-3">

              <div className="hidden sm:flex items-center gap-2 text-sm text-slate-500">
                <HistoryIcon size={17} />
                Debate History
              </div>

              <button
                onClick={toggleTheme}
                aria-label="Toggle theme"
                className={`inline-flex items-center justify-center h-10 w-10 rounded-xl border transition-all ${
                  dark
                    ? "border-slate-700 bg-slate-900 text-slate-300 hover:text-white hover:border-slate-500"
                    : "border-slate-200 bg-white text-slate-600 hover:text-slate-900 hover:border-slate-300"
                }`}
              >
                {dark ? (
                  <Sun size={17} />
                ) : (
                  <Moon size={17} />
                )}
              </button>

            </div>

          </div>
        </div>
      </header>

      {/* Main */}
      <main className="max-w-7xl mx-auto px-6 lg:px-10 py-12">

        {/* Heading */}
        <section className="mb-10 max-w-3xl">

          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-400/20 bg-indigo-400/5 px-3 py-1.5 text-xs text-indigo-500">
            <span className="h-1.5 w-1.5 rounded-full bg-indigo-400" />
            Practice History
          </div>

          <h2
            className={`mt-5 text-4xl md:text-5xl font-semibold tracking-tight ${
              dark ? "text-white" : "text-slate-900"
            }`}
          >
            Your debate sessions
            <span className="block text-slate-500">
              in one place.
            </span>
          </h2>

          <p
            className={`mt-5 leading-7 ${
              dark ? "text-slate-400" : "text-slate-600"
            }`}
          >
            Review previous topics, your rebuttals, and the feedback
            generated by Oratio AI.
          </p>

        </section>

        {/* Empty State */}
        {history.length === 0 ? (
          <section
            className={`rounded-3xl border p-12 text-center ${
              dark
                ? "border-slate-800 bg-slate-900/60"
                : "border-slate-200 bg-white"
            }`}
          >
            <div
              className={`mx-auto h-14 w-14 rounded-2xl border flex items-center justify-center ${
                dark
                  ? "border-slate-700 bg-slate-950"
                  : "border-slate-200 bg-slate-50"
              }`}
            >
              <HistoryIcon
                size={24}
                className="text-slate-500"
              />
            </div>

            <h3
              className={`mt-6 text-xl font-semibold ${
                dark ? "text-white" : "text-slate-900"
              }`}
            >
              No debate sessions yet
            </h3>

            <p className="mt-2 text-sm text-slate-500 max-w-md mx-auto">
              Complete your first debate session and your analysis will appear here.
            </p>
          </section>
        ) : (
          <section className="space-y-5">

            {history.map((item, index) => {
              const isOpen = openIndex === index;

              return (
                <article
                  key={index}
                  className={`rounded-3xl border overflow-hidden transition-all duration-300 ${
                    dark
                      ? "border-slate-800 bg-slate-900/60 hover:border-slate-700"
                      : "border-slate-200 bg-white hover:border-slate-300"
                  }`}
                >

                  {/* Summary */}
                  <button
                    onClick={() => toggleItem(index)}
                    className="w-full text-left px-6 py-6 md:px-7 md:py-7"
                  >
                    <div className="flex items-start justify-between gap-6">

                      <div className="min-w-0">

                        <p className="text-xs uppercase tracking-[0.18em] text-indigo-500">
                          Debate Session {index + 1}
                        </p>

                        <h3
                          className={`mt-2 text-xl md:text-2xl font-semibold break-words ${
                            dark ? "text-white" : "text-slate-900"
                          }`}
                        >
                          {item.topic}
                        </h3>

                        <p className="mt-2 text-sm text-slate-500">
                          View your rebuttal and evaluation report
                        </p>

                      </div>

                      <div
                        className={`shrink-0 h-10 w-10 rounded-xl border flex items-center justify-center ${
                          dark
                            ? "border-slate-700 bg-slate-950 text-slate-400"
                            : "border-slate-200 bg-slate-50 text-slate-500"
                        }`}
                      >
                        {isOpen ? (
                          <ChevronUp size={18} />
                        ) : (
                          <ChevronDown size={18} />
                        )}
                      </div>

                    </div>
                  </button>

                  {/* Details */}
                  {isOpen && (
                    <div
                      className={`border-t px-6 py-6 md:px-7 md:py-7 space-y-6 ${
                        dark
                          ? "border-slate-800"
                          : "border-slate-200"
                      }`}
                    >

                      {/* Your Response */}
                      <div>

                        <div className="flex items-center gap-2 text-sm font-medium">
                          <MessageSquare
                            size={17}
                            className="text-indigo-500"
                          />

                          <span
                            className={
                              dark
                                ? "text-slate-300"
                                : "text-slate-700"
                            }
                          >
                            Your Response
                          </span>
                        </div>

                        <div
                          className={`mt-3 rounded-2xl border p-5 ${
                            dark
                              ? "border-slate-800 bg-slate-950/70"
                              : "border-slate-200 bg-slate-50"
                          }`}
                        >
                          <p
                            className={`whitespace-pre-wrap text-sm leading-7 ${
                              dark
                                ? "text-slate-400"
                                : "text-slate-600"
                            }`}
                          >
                            {item.user_argument ||
                              "No response recorded."}
                          </p>
                        </div>

                      </div>

                      {/* AI Feedback */}
                      <div>

                        <div className="flex items-center gap-2 text-sm font-medium">

                          <FileText
                            size={17}
                            className="text-violet-500"
                          />

                          <span
                            className={
                              dark
                                ? "text-slate-300"
                                : "text-slate-700"
                            }
                          >
                            Evaluation Report
                          </span>

                        </div>

                        <div
                          className={`mt-3 rounded-2xl border p-5 ${
                            dark
                              ? "border-slate-800 bg-slate-950/70"
                              : "border-slate-200 bg-slate-50"
                          }`}
                        >
                          <pre
                            className={`whitespace-pre-wrap font-sans text-sm leading-7 ${
                              dark
                                ? "text-slate-400"
                                : "text-slate-600"
                            }`}
                          >
                            {item.feedback ||
                              "No evaluation available."}
                          </pre>
                        </div>

                      </div>

                    </div>
                  )}

                </article>
              );
            })}

          </section>
        )}

      </main>
    </div>
  );
}